### ISSUE TITLE
please enable the font equivalent to runtime dynamic linking with system copy of forkawesome

### ISSUE THREAD

**Issue by sten0** [Martchus/qtforkawesome#2]
Hi @Martchus,

I finally found some time to review @hrittich's work, and read your note

> By the way, the next release will require the additional dependency `qtforkawesome` and the _current_ release is actually still bundling icons from Font Awesome which might be problematic for Debian. So you most likely want to wait for the next release anyways.

https://github.com/Martchus/cpp-utilities/pull/20#pullrequestreview-769501526

I'm not sure what the right word to use is when speaking about fonts, but in Debian we need to use the system `fonts-fork-awesome` package that @aviau packaged, like Syncthing uses it.

Regards,
Nicholas

**Comment by Martchus** [comment]
I don't know what the `fonts-fork-awesome` package contains but as stated in https://github.com/Martchus/qtforkawesome#providing-the-font-file you need some font file and the icons definitions (YAML file). Both will be incorporated into this library at build time. For the icons definitions that also makes totally sense because they're converted to a C++ enum and hash-map. The font file itself *could* theoretically be located at runtime but I'm not sure whether that make most sense. The current approach makes sure that the icon definitions always match the actual font file.

By the way, somehow I doubt that Syncthing itself loads any fonts from the system as they're generally also just build resources into the application binary.¹

---

¹ It looks like Syncthing indeed has a copy of Fork Awesome in their repo and the script https://github.com/syncthing/syncthing/blob/main/script/genassets.go bundles the files at build-time by incorporating the files into the binary (similar to how the build script of `qtforkawesome` does it).

**Comment by sten0** [comment]
Hi @Martchus,

I'm sorry for the delay, and that I'm consistently horrible with such things. 
 Belated thank you for your reply, and I agree with your analysis and rationale!  I read it soon after you sent it, and thought I had replied, but I guess that discussion must have been with @hrittich on Debian infrastructure.  A résumé of the Debian side of this same discussion is thus: Yes, that's how Syncthing does it in Debian, and that's a precedent we can follow.

Oh and here is a packaging update:  We're currently stalled at martchus-cpp-utilities martchus-qtutilities.  @hrittich, would you like to reply to that Debian Policy bug that requests the perspective of someone not yet involved in the discussion, or would you like me to make the changes required to make your packages compliant with Policy 4.6.0? (for anyone reading this who doesn't know what that is, it's a strict code about what packages are and are not permitted to do, plus best practices, and--yes--some pedantic stuff too)

**Comment by Martchus** [comment]
Thanks for the packaging update. Interesting to hear. I suppose https://github.com/Martchus/syncthingtray/issues/33 would be the better place to talk about it (where I've already tried to keep track of what you're doing).

---

I'll keep this issue open as a feature request although I personally don't intend to work on it (for reasons stated in the previous comment).

**Comment by sten0** [comment]
I'll go ahead and close it then, no point cluttering your issue tracker (cognitive load, etc.) ;-)  Thank you for you willingness to keep it open though!  Really, I think upstream Syncthing would need to change before it would make sense to talk about it doing the same here.
